version: '3.8'

services:
  developerevaluation.webapi:
    container_name: developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}developerevaluationwebapi
    build:
      context: .
      dockerfile: src/DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  developerevaluation.database:
    container_name: developer_evaluation_database
    image: postgres:13

    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped

  # developerevaluation.nosql:
  #   container_name: developer_evaluation_nosql 
  #   image: mongo:8.0    
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: developer
  #       MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #     - "27017"

  # developerevaluation.cache:
  #   container_name: developer_evaluation_cache 
  #   image: redis:7.4.1-alpine     
  #   command: redis-server --requirepass ev@luAt10n
  #   environment:
  #      MONGO_INITDB_ROOT_USERNAME: developer
  #      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #      - "6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

# networks:
#   default:
#     driver: bridge